

services:
  spring-boot-server:
    container_name: spring-boot-container
    image: spring-boot-app
    build: ./
    ports:
      - ${SPRING_BOOT_PORT}:8080
    depends_on:
      mongodb-server:
        condition: service_healthy
    healthcheck:
      test: [
        "CMD", "curl", "http://localhost:8080/status"
      ]
    networks:
      - backend
    command: [
      "--server.port=${SPRING_BOOT_PORT}",
      "--spring.mongodb.host=mongodb-server",
      "--spring.mongodb.port=27017",
      "--spring.mongodb.database=${SPLIT_EXPENSE_DB}",
      "--spring.mongodb.username=${SPLIT_EXPENSE_DB_USER}",
      "--spring.mongodb.password=${SPLIT_EXPENSE_DB_PASSWORD}",
      "--spring.mongodb.authentication-database=admin"
    ]

  mongodb-server:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - ${MONGO_DB_PORT}:27017
    volumes:
      - split_cost_db:/data/db
      - split_cost_config:/data/configdb
    healthcheck:
      test: [
        "CMD", "mongosh", "--host", "localhost", "--port", "27017",
        "--quiet", "--eval", "db.adminCommand({ping:1})"
      ]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - backend

  init-db:
    image: alpine/mongosh
    depends_on:
      mongodb-server:
        condition: service_healthy
    restart: "no"
    volumes:
      - ./db_scripts/init.js:/scripts/init.js:ro
    networks:
      - backend
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      SPLIT_EXPENSE_DB: ${SPLIT_EXPENSE_DB}
      SPLIT_EXPENSE_DB_USER: ${SPLIT_EXPENSE_DB_USER}
      SPLIT_EXPENSE_DB_PASSWORD: ${SPLIT_EXPENSE_DB_PASSWORD}
    command: ["mongosh",
              "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb-server:27017/admin",
              "/scripts/init.js"
    ]

volumes:
  split_cost_db:
    external: true
  split_cost_config:
    external: true

networks:
  backend:
    driver: bridge