server.port=8080

spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=split_expenses
spring.mongodb.username=split_cost_user
spring.mongodb.password=CaconicalCarCrash5412!!
spring.mongodb.authentication-database=admin