name: build_project

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - 'dev'
      - 'main'

jobs:
  gradle_build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build with gradle
        run: ./gradlew build

      - name: Test with gradle
        run: ./gradlew test
